owner: nextpost-tech
repo: status

sites:
  - name: Nextpost.tech
    url: https://nextpost.tech
  - name: REST API
    url: https://nextpost.tech/graftype-api/?action_type=now&token=$API_KEY
    method: GET
    maxResponseTime: 30000
  - name: TikTok REST API
    url: https://nextpost.tech/tiktok-api/getVideoByID?video_id=6986776740685171974&license_key=$API_KEY
    method: GET
    maxResponseTime: 30000

status-website:
  cname: status.nextpost.tech
  logoUrl: https://nextpost.tech/wp-content/uploads/2022/04/nextpost-new-logo-black.png
  name: Nextpost.tech Status
  introTitle: Nextpost.tech Status
  introMessage: Our status page uses **real-time** data from our [Nextpost.tech](https://nextpost.tech) servers.
  navbar:
    - title: Status
      href: /
