owner: evelode
repo: status

assignees:
  -  sergeykomlev

sites:
  - name: Evelode
    url: https://evelode.com
    icon: https://evelode.com/wp-content/uploads/2024/02/evelode-logo.png
    maxResponseTime: 30000
    expectedStatusCodes:
      - 200
  - name: Evelode REST API
    url: https://evelode.com/graftype-api/?action_type=now&token=$API_KEY
    icon: https://evelode.com/wp-content/uploads/2024/02/evelode-logo.png
    method: GET
    maxResponseTime: 30000
    expectedStatusCodes:
      - 200
      - 502
      - 521
      - 403
  - name: TikTok REST API (SFO3)
    url: https://tiktok.evelode.com/getVideoByID?video_id=7106855913906081070&license_key=$API_KEY&cache_timeout=0
    icon: https://evelode.com/wp-content/uploads/edd/2022/02/Nextpost.tech-1.jpg
    method: GET
    maxResponseTime: 30000
    expectedStatusCodes:
      - 200
      - 502
      - 521
      - 403

status-website:
  cname: status.evelode.com
  logoUrl: https://evelode.com/wp-content/uploads/2024/02/evelode-logo.png
  favicon: https://evelode.com/wp-content/uploads/2024/02/evelode-logo.png
  name: Evelode Status
  introTitle: "**Evelode Status** is the uptime monitor and status page"
  introMessage: Our status page uses a **real-time** data from [Evelode](https://evelode.com) servers.
  navbar:
    - title: Homepage
      href: /
      
commitMessages:
  commitAuthorName: "Evelode"
  commitAuthorEmail: "contact@evelode.com"
