owner: nextpost-tech
repo: tiktok-api-status

sites:
  - name: /getNoWatermarkUrl
    url: https://nextpost.tech/tiktok-api/getNoWatermarkUrl?video_url=https://www.tiktok.com/@iamcardib/video/6986776740685171974&license_key=API_KEY
    method: POST
    maxResponseTime: 60000
    

status-website:
  cname: tiktok.nextpost.tech
  logoUrl: https://nextpost.tech/wp-content/uploads/2022/04/nextpost-new-logo-black.png
  name: TikTok REST API Status
  introTitle: TikTok REST API Status
  introMessage: Our status page uses **real-time** data from our Nextpost.tech TikTok REST API server. Try our [Trial license plan](https://nextpost.tech/downloads/tiktok-rest-api/) and test all API endpoints before buying a license.
  navbar:
    - title: Status
      href: /
    - title: TikTok REST API
      href: https://nextpost.tech/downloads/tiktok-rest-api/
    - title: GitHub
      href: https://github.com/$OWNER/
